environment = "JULIA_DEPOT_PATH='/lustre/fs23/group/nic/tangelides/.julia:$JULIA_DEPOT_PATH'"

executable = /lustre/fs23/group/nic/tangelides/julia-1.7.2/bin/julia

arguments = /afs/ifh.de/user/a/angeltak/Schwinger-Wilson-MPS/testing.jl

transfer_input_files = /afs/ifh.de/user/a/angeltak/Schwinger-Wilson-MPS/testing.jl

should_transfer_files = IF_NEEDED

request_memory = $(mem)G

+RequestRuntime = 144*60*60

max_retries = 5

output = /afs/ifh.de/user/a/angeltak/logs/testing_$(Cluster)_$(Process).out

error = /afs/ifh.de/user/a/angeltak/logs/testing_$(Cluster)_$(Process).error

log = /afs/ifh.de/user/a/angeltak/logs/testing_$(Cluster)_$(Process).log

queue 1